name: sparkles

services:
  web:
    image: ghcr.io/listlessbird/sparkles-web:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - RENDERER_URL=http://renderer:3001
      - NEXT_PUBLIC_BASE_URL=http://web:3000
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CF_API_KEY=${CF_API_KEY}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - CF_ACCOUNT_ID=${CF_ACCOUNT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - ASSEMBLY_API_KEY=${ASSEMBLY_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - D1_ID=${D1_ID}
      - D1_KEY=${D1_KEY}
      - CF_ID=${CF_ID}

  renderer:
    image: ghcr.io/listlessbird/sparkles-renderer:latest
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

networks:
  default:
    name: app-network
