name: sparkles

services:
  web:
    image: web-ui
    env_file:
      - .env
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - RENDERER_URL=http://renderer:3001
      - NEXT_PUBLIC_BASE_URL=http://web:3000
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CF_API_KEY=${CF_API_KEY}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - CF_ACCOUNT_ID=${CF_ACCOUNT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - ASSEMBLY_API_KEY=${ASSEMBLY_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - D1_ID=${D1_ID}
      - D1_KEY=${D1_KEY}
      - CF_ID=${CF_ID}

  renderer:
    image: ai-short-gen-renderer
    build: 
      context: ./renderer
    ports:
      - "3001:3001"

networks:
  default:
    name: app-network
