FROM node:20-bookworm AS base

RUN curl -fsSL https://bun.sh/install | bash

RUN apt-get update && apt install -y \
    libnss3 \
    libdbus-1-3 \
    libatk1.0-0 \
    libgbm-dev \
    libasound2 \
    libxrandr2 \
    libxkbcommon-dev \
    libxfixes3 \
    libxcomposite1 \
    libxdamage1 \
    libatk-bridge2.0-0 \
    libcups2

ENV PATH="/root/.bun/bin:$PATH"

WORKDIR /usr/src/app

FROM base AS install
RUN mkdir -p /temp/dev /temp/prod
COPY package.json bun.lockb /temp/dev/
COPY package.json bun.lockb /temp/prod/
RUN cd /temp/dev && bun install --frozen-lockfile
RUN cd /temp/prod && bun install --frozen-lockfile --production
RUN cd /temp/prod && bunx remotion browser ensure

FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ENV NODE_ENV=production

FROM base AS release
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /usr/src/app/src ./src
COPY --from=prerelease /usr/src/app/package.json .

RUN chmod -R 755 /usr/src/app/node_modules/@remotion
RUN chown -R node:node /usr/src/app/

USER node
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "run", "src/index.ts" ]
