FROM imbios/bun-node:latest-current-alpine AS base

ARG NEXT_PUBLIC_BASE_URL=sparkles.listlessbird.dev

FROM base AS deps
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
RUN npm install --os=linux --cpu=x64 sharp --force

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_SHARP_PATH=/app/node_modules/sharp
RUN bun run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_TELEMETRY_DISABLED 1
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/node_modules/sharp ./node_modules/sharp

EXPOSE 3000
CMD ["bun", "run", "server.js"]